### ISSUE TITLE
Update 1.6 documentation

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#128]
I'm creating this issue to group all issues related to the Kikaha's documentation. 
If someone else find any other gap at the documentation, please, fill another issues or send us a note at the comments.

- [x] #133 Include missing details at sample codes, like 'package' and 'import's
- [x] #132 Section "Routing with Undertow API" is empty.
- [x] #123 Missing **CDI** topic at the documentation
- [x] #121 Missing **Mustache** module documentation
- [x] Missing **ViburDBCP** documentation
- [x] Missing _DefaultResponse_ API documentation
- [x] Improve Hazelcast documentation
- [x] #114 Missing a documentation about the REST API Security Context
- [x] Improve Kikaha CLI documentation
- [x] Create a '1 Minute tutorial' about project creation with Kikaha
- [x] Update Server configuration

**Comment by spencode** [comment]
Hi.

1. Section "Routing with Undertow API" is empty.
2. In the examples, sometimes missing required "package" and "import".

**Comment by miere** [comment]
I've included two issues regarding your documentation issues. #133 and #132.
Also, I've added both here, so you can keep track of the progress of the documentation process.

About the due date, you can follow the Roadmap through the Github issues. [This link](https://github.com/Skullabs/kikaha/milestones) would be useful to have an overview about should be doing at the next few months.
