### ISSUE TITLE
Documentation topics for 2.0.0 version

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#144]
- [ ] #111 Create a detailed tutorial about User Session
- [ ] #117 Document how users can handle uncaught exceptions
- [ ] #118 Document the MailSender module
- [ ] #119 Document the Test API based on JUnit
- [ ] Document the expedition process with Kikaha
- [x] Session clustering and distribution with Hazelcast
- [x] New configuration module
